import type { WooProduct } from "./types";

export const DEMO_PRODUCTS: WooProduct[] = [
  // HOODIES (cat id 17)
  {
    id: 1,
    name: "VOID Oversize Hoodie",
    slug: "void-oversize-hoodie",
    price: "1450",
    regular_price: "1450",
    on_sale: false,
    stock_quantity: 12,
    stock_status: "instock",
    featured: true,
    description: "Hoodie oversize en color negro profundo. Grafico YAYAS bordado en pecho. 100% algodón orgánico, 380g/m². El essential de tu guardarropa oscuro.",
    short_description: "Hoodie oversize void con logo bordado",
    categories: [{ id: 17, name: "Hoodies", slug: "hoodies" }],
    images: [
      { id: 1, src: "https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=800&h=1000&fit=crop", alt: "VOID Oversize Hoodie" },
      { id: 2, src: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&h=1000&fit=crop", alt: "VOID Oversize Hoodie Back" },
    ],
    sku: "VOID-HOOD-001",
    tags: ["oversize", "bordo"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL", "XXL"] }],
  },
  {
    id: 2,
    name: "OBSIDIAN Pullover Hoodie",
    slug: "obsidian-pullover-hoodie",
    price: "1350",
    regular_price: "1350",
    on_sale: false,
    stock_quantity: 8,
    stock_status: "instock",
    featured: true,
    description: "Hoodie pullover sin zipper en tono obsidiana. Estampado en espalda con graphics rituales. Ideal para layering.",
    short_description: "Hoodie pullover obsidiana con graphics",
    categories: [{ id: 17, name: "Hoodies", slug: "hoodies" }],
    images: [
      { id: 3, src: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&h=1000&fit=crop", alt: "OBSIDIAN Pullover" },
      { id: 4, src: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&h=1000&fit=crop", alt: "OBSIDIAN Pullover Detail" },
    ],
    sku: "OBS-HOOD-002",
    tags: ["pullover", "graphics"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
  {
    id: 3,
    name: "CAOS Zip-Up Hoodie",
    slug: "caos-zip-up-hoodie",
    price: "1590",
    regular_price: "1590",
    on_sale: false,
    stock_quantity: 6,
    stock_status: "instock",
    featured: false,
    description: "Hoodie zip-up half-collar en negro. Texto 'CAOS' bordado en brazo. Dos bolsillos frontales con cierre.",
    short_description: "Zip-up hoodie con texto CAOS",
    categories: [{ id: 17, name: "Hoodies", slug: "hoodies" }],
    images: [
      { id: 5, src: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&h=1000&fit=crop", alt: "CAOS Zip-Up" },
    ],
    sku: "CAOS-HOOD-001",
    tags: ["zip", "texto"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL", "XXL"] }],
  },
  {
    id: 4,
    name: "SHADOW Heavy Hoodie",
    slug: "shadow-heavy-hoodie",
    price: "1650",
    regular_price: "1850",
    on_sale: true,
    stock_quantity: 4,
    stock_status: "instock",
    featured: false,
    description: "Hoodie de tela pesada 450g/m². El más cálido de la colección. Grafico grande en espalda con logo YAYAS.",
    short_description: "Hoodie pesado shadow con logo",
    categories: [{ id: 17, name: "Hoodies", slug: "hoodies" }],
    images: [
      { id: 6, src: "https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=800&h=1000&fit=crop", alt: "SHADOW Heavy" },
    ],
    sku: "SHAD-HOOD-001",
    tags: ["heavy", "sale"],
    attributes: [{ id: 1, name: "Talla", options: ["M", "L", "XL"] }],
  },

  // PLAYERAS (cat id 18)
  {
    id: 5,
    name: "VOID TEXTURE Tee",
    slug: "void-texture-tee",
    price: "590",
    regular_price: "850",
    on_sale: true,
    stock_quantity: 20,
    stock_status: "instock",
    featured: true,
    description: "Playera oversize con textura canvas única. 100% algodón orgánico mexicano. Logo YAYAS pequeño en pecho.",
    short_description: "Playera void textura canvas",
    categories: [{ id: 18, name: "Playeras", slug: "playeras" }],
    images: [
      { id: 7, src: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&h=1000&fit=crop", alt: "VOID TEXTURE Tee" },
      { id: 8, src: "https://images.unsplash.com/photo-1618354691438-25bc04584c23?w=800&h=1000&fit=crop", alt: "VOID TEXTURE Tee Back" },
    ],
    sku: "VOID-TEE-001",
    tags: ["oversize", "sale"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL", "XXL"] }],
  },
  {
    id: 6,
    name: "ETERNITY Longsleeve",
    slug: "eternity-longsleeve",
    price: "750",
    regular_price: "750",
    on_sale: false,
    stock_quantity: 15,
    stock_status: "instock",
    featured: true,
    description: "Longsleeve con print frontal 'ETERNITY'. Tela suave 100%algodón. Perfecta para noches frías.",
    short_description: "Longsleeve eternity con print",
    categories: [{ id: 18, name: "Playeras", slug: "playeras" }],
    images: [
      { id: 9, src: "https://images.unsplash.com/photo-1611095962005-9c6b5a0a92f0?w=800&h=1000&fit=crop", alt: "ETERNITY Longsleeve" },
    ],
    sku: "ETERN-LONG-001",
    tags: ["longsleeve", "print"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
  {
    id: 7,
    name: "CREAM Essential Tee",
    slug: "cream-essential-tee",
    price: "490",
    regular_price: "490",
    on_sale: false,
    stock_quantity: 25,
    stock_status: "instock",
    featured: false,
    description: "Playera básica en tono cream que contrasta con outfits oscuros. Corte clásico, no oversize.",
    short_description: "Playera cream esencial",
    categories: [{ id: 18, name: "Playeras", slug: "playeras" }],
    images: [
      { id: 10, src: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=1000&fit=crop", alt: "CREAM Essential Tee" },
    ],
    sku: "CREA-TEE-001",
    tags: ["essential", "basica"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
  {
    id: 8,
    name: "CARBON Oversize Tee",
    slug: "carbon-oversize-tee",
    price: "650",
    regular_price: "650",
    on_sale: false,
    stock_quantity: 18,
    stock_status: "instock",
    featured: false,
    description: "Playera oversize con logo YAYAS bordado en pecho. Canvas 240g. La playera más versátil de la colección.",
    short_description: "Playera oversize carbon bordada",
    categories: [{ id: 18, name: "Playeras", slug: "playeras" }],
    images: [
      { id: 11, src: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=1000&fit=crop", alt: "CARBON Oversize Tee" },
    ],
    sku: "CARB-TEE-001",
    tags: ["oversize", "bordo"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL", "XXL"] }],
  },
  {
    id: 9,
    name: "ASH Thermal Shirt",
    slug: "ash-thermal-shirt",
    price: "680",
    regular_price: "680",
    on_sale: false,
    stock_quantity: 12,
    stock_status: "instock",
    featured: false,
    description: "Thermal de manga larga en tono ash (gris cenizo). Tela térmica ligera con costuras reforzadas.",
    short_description: "Thermal ash manga larga",
    categories: [{ id: 18, name: "Playeras", slug: "playeras" }],
    images: [
      { id: 12, src: "https://images.unsplash.com/photo-1611095962005-9c6b5a0a92f0?w=800&h=1000&fit=crop", alt: "ASH Thermal" },
    ],
    sku: "ASH-THER-001",
    tags: ["thermal", "manga-larga"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },

  // CHAQUETAS (cat id 19)
  {
    id: 10,
    name: "SMOKE Bomber Jacket",
    slug: "smoke-bomber-jacket",
    price: "1890",
    regular_price: "2200",
    on_sale: true,
    stock_quantity: 5,
    stock_status: "instock",
    featured: true,
    description: "Bomber jacket en tono smoke con forro de satén. Estampado de calaveras en espalda. El statement piece de la colección.",
    short_description: "Bomber jacket smoke con forro satén",
    categories: [{ id: 19, name: "Chaquetas", slug: "chaquetas" }],
    images: [
      { id: 13, src: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1000&fit=crop", alt: "SMOKE Bomber Jacket" },
    ],
    sku: "SMOK-BOM-001",
    tags: ["bomber", "sale"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
  {
    id: 11,
    name: "NIGHT Leather Look Jacket",
    slug: "night-leather-look-jacket",
    price: "2150",
    regular_price: "2150",
    on_sale: false,
    stock_quantity: 4,
    stock_status: "instock",
    featured: true,
    description: "Chaqueta leather look en poliuretano premium. Diseño minimalista con cierre diagonal. El look delgada sin esfuerzo.",
    short_description: "Chaqueta leather look night",
    categories: [{ id: 19, name: "Chaquetas", slug: "chaquetas" }],
    images: [
      { id: 14, src: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1000&fit=crop", alt: "NIGHT Leather Look" },
    ],
    sku: "NIGHT-LJ-001",
    tags: ["leather-look", "premium"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L"] }],
  },
  {
    id: 12,
    name: "ROCKET Varsity Jacket",
    slug: "rocket-varsity-jacket",
    price: "2450",
    regular_price: "2450",
    on_sale: false,
    stock_quantity: 3,
    stock_status: "instock",
    featured: false,
    description: "Varsity jacket con parches bordados YAYAS en brazo y espalda. Manga y cuello de mezclilla. Pieza de colección.",
    short_description: "Varsity jacket con parches YAYAS",
    categories: [{ id: 19, name: "Chaquetas", slug: "chaquetas" }],
    images: [
      { id: 15, src: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1000&fit=crop", alt: "ROCKET Varsity" },
    ],
    sku: "ROCK-VAR-001",
    tags: ["varsity", "parches"],
    attributes: [{ id: 1, name: "Talla", options: ["M", "L", "XL"] }],
  },

  // PANTALONES (cat id 20)
  {
    id: 13,
    name: "ASH Wide-Leg Pants",
    slug: "ash-wide-leg-pants",
    price: "980",
    regular_price: "980",
    on_sale: false,
    stock_quantity: 15,
    stock_status: "instock",
    featured: false,
    description: "Pantalón wide-leg en tela ash. Cómodo, oversize, oscuro. El corte más cómodo para el día a día.",
    short_description: "Pantalón wide-leg ash",
    categories: [{ id: 20, name: "Pantalones", slug: "pantalones" }],
    images: [
      { id: 16, src: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&h=1000&fit=crop", alt: "ASH Wide-Leg Pants" },
    ],
    sku: "ASH-WID-001",
    tags: ["wide-leg", "oversize"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
  {
    id: 14,
    name: "CARGO VOID Pants",
    slug: "cargo-void-pants",
    price: "1150",
    regular_price: "1150",
    on_sale: false,
    stock_quantity: 12,
    stock_status: "instock",
    featured: false,
    description: "Cargo pants con 6 bolsillos. Tela ripstop resistente al agua. Corte holgado. Para quienes necesitan función y estilo.",
    short_description: "Cargo pants void con 6 bolsillos",
    categories: [{ id: 20, name: "Pantalones", slug: "pantalones" }],
    images: [
      { id: 17, src: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&h=1000&fit=crop", alt: "CARGO VOID Pants" },
    ],
    sku: "CARG-VOI-001",
    tags: ["cargo", "funcional"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL", "XXL"] }],
  },
  {
    id: 15,
    name: "SMOKE Joggers",
    slug: "smoke-joggers",
    price: "850",
    regular_price: "850",
    on_sale: false,
    stock_quantity: 18,
    stock_status: "instock",
    featured: false,
    description: "Joggers de tela técnica con cordón ajustable. Bolsillos con cierre. El comfort del streetwear premium.",
    short_description: "Joggers smoke tela técnica",
    categories: [{ id: 20, name: "Pantalones", slug: "pantalones" }],
    images: [
      { id: 18, src: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&h=1000&fit=crop", alt: "SMOKE Joggers" },
    ],
    sku: "SMOK-JOG-001",
    tags: ["joggers", "comfy"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
  {
    id: 16,
    name: "VOID Cargo Shorts",
    slug: "void-cargo-shorts",
    price: "680",
    regular_price: "800",
    on_sale: true,
    stock_quantity: 10,
    stock_status: "instock",
    featured: false,
    description: "Shorts cargo con 4 bolsillos. Tela ligera para verano. Corte holgado por encima de la rodilla.",
    short_description: "Cargo shorts void",
    categories: [{ id: 20, name: "Pantalones", slug: "pantalones" }],
    images: [
      { id: 19, src: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&h=1000&fit=crop", alt: "VOID Cargo Shorts" },
    ],
    sku: "VOID-SHORT-001",
    tags: ["shorts", "sale"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },

  // ACCESORIOS (cat id 21)
  {
    id: 17,
    name: "YAYAS 5-Panel Cap",
    slug: "yayas-5panel-cap",
    price: "420",
    regular_price: "420",
    on_sale: false,
    stock_quantity: 30,
    stock_status: "instock",
    featured: true,
    description: "Gorra 5-panel bordada con logo YAYAS. Cierre snapback ajustable. Negro profundo.",
    short_description: "Gorra 5-panel YAYAS bordada",
    categories: [{ id: 21, name: "Accesorios", slug: "accesorios" }],
    images: [
      { id: 20, src: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&h=1000&fit=crop", alt: "YAYAS 5-Panel Cap" },
    ],
    sku: "YAYA-CAP-001",
    tags: ["gorra", "bordo"],
    attributes: [],
  },
  {
    id: 18,
    name: "GOTH Bucket Hat",
    slug: "goth-bucket-hat",
    price: "380",
    regular_price: "380",
    on_sale: false,
    stock_quantity: 20,
    stock_status: "instock",
    featured: false,
    description: "Bucket hat en negro. Tela ripstop resistente al agua. Logo YAYAS bordado pequeño.",
    short_description: "Bucket hat goth negro",
    categories: [{ id: 21, name: "Accesorios", slug: "accesorios" }],
    images: [
      { id: 21, src: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&h=1000&fit=crop", alt: "GOTH Bucket Hat" },
    ],
    sku: "GOTH-BUCK-001",
    tags: ["bucket", "summer"],
    attributes: [],
  },
  {
    id: 19,
    name: "CARBON Crossbody Bag",
    slug: "carbon-crossbody-bag",
    price: "680",
    regular_price: "850",
    on_sale: true,
    stock_quantity: 8,
    stock_status: "instock",
    featured: false,
    description: "Bolsa crossbody en nylon negro. Tela resistente al agua. Correa ajustable. El accesorio daily perfecto.",
    short_description: "Crossbody bag carbono nylon",
    categories: [{ id: 21, name: "Accesorios", slug: "accesorios" }],
    images: [
      { id: 22, src: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&h=1000&fit=crop", alt: "CARBON Crossbody Bag" },
    ],
    sku: "CARB-BAG-001",
    tags: ["bolsa", "sale"],
    attributes: [],
  },
  {
    id: 20,
    name: "GOLD Chain Necklace",
    slug: "gold-chain-necklace",
    price: "350",
    regular_price: "450",
    on_sale: true,
    stock_quantity: 15,
    stock_status: "instock",
    featured: false,
    description: "Cadena dorada con dije YAYAS personalizado. Acero inoxidable chapado en oro 18k. 55cm con extensible de 5cm.",
    short_description: "Cadena dorada con dije YAYAS",
    categories: [{ id: 21, name: "Accesorios", slug: "accesorios" }],
    images: [
      { id: 23, src: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=1000&fit=crop", alt: "GOLD Chain Necklace" },
    ],
    sku: "GOLD-CHAIN-001",
    tags: ["cadena", "joyeria", "sale"],
    attributes: [],
  },
  {
    id: 21,
    name: "VOID Beanie",
    slug: "void-beanie",
    price: "290",
    regular_price: "290",
    on_sale: false,
    stock_quantity: 25,
    stock_status: "instock",
    featured: false,
    description: "Beanie en punto tejido suave. Negro con logo YAYAS bordado en frente. Talla única.",
    short_description: "Beanie void bordado",
    categories: [{ id: 21, name: "Accesorios", slug: "accesorios" }],
    images: [
      { id: 24, src: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&h=1000&fit=crop", alt: "VOID Beanie" },
    ],
    sku: "VOID-BEAN-001",
    tags: ["beanie", "invierno"],
    attributes: [],
  },
  {
    id: 22,
    name: "BLOOD Ring Set",
    slug: "blood-ring-set",
    price: "280",
    regular_price: "280",
    on_sale: false,
    stock_quantity: 20,
    stock_status: "instock",
    featured: false,
    description: "Set de 3 anillos de acero quirúrgico. Acabado negro. Grabado láser YAYAS. Set de tallas S/M/L.",
    short_description: "Set anillos sangre acero quirúrgico",
    categories: [{ id: 21, name: "Accesorios", slug: "accesorios" }],
    images: [
      { id: 25, src: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=1000&fit=crop", alt: "BLOOD Ring Set" },
    ],
    sku: "BLOOD-RING-001",
    tags: ["anillos", "joyeria"],
    attributes: [],
  },

  // PREMIUM (cat id 22)
  {
    id: 23,
    name: "NOCHE DE MUERTOS Limited Hoodie",
    slug: "noche-de-muertos-hoodie",
    price: "2250",
    regular_price: "2250",
    on_sale: false,
    stock_quantity: 30,
    stock_status: "instock",
    featured: true,
    description: "Hoodie edición limitada Halloween. Grafico exclusivo 'Noche de Muertos' bordado en espalda. Solo 50 piezas numeradas. 100% algodón orgánico.",
    short_description: "EDICIÓN LIMITADA hoodie noche de muertos",
    categories: [{ id: 22, name: "Premium", slug: "premium" }],
    images: [
      { id: 26, src: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&h=1000&fit=crop", alt: "NOCHE DE MUERTOS Hoodie" },
    ],
    sku: "NDM-HOOD-LTD",
    tags: ["limited", "halloween", "edicion-especial"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL", "XXL"] }],
  },
  {
    id: 24,
    name: "SANTO GATO Premium Tee",
    slug: "santo-gato-premium-tee",
    price: "890",
    regular_price: "890",
    on_sale: false,
    stock_quantity: 50,
    stock_status: "instock",
    featured: false,
    description: "Edición especial con illustration exclusiva 'Santo Gato' — nuestro mascot secreto. Print de alta calidad en espalda completa.",
    short_description: "Premium tee Santo Gato illustration",
    categories: [{ id: 22, name: "Premium", slug: "premium" }],
    images: [
      { id: 27, src: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&h=1000&fit=crop", alt: "SANTO GATO Premium Tee" },
    ],
    sku: "GATO-TEE-PRE",
    tags: ["gato", "edicion-especial", "ilustracion"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
  {
    id: 25,
    name: "ECLIPSE Gold Foil Hoodie",
    slug: "eclipse-gold-foil-hoodie",
    price: "2890",
    regular_price: "2890",
    on_sale: false,
    stock_quantity: 20,
    stock_status: "instock",
    featured: true,
    description: "El hoodie más exclusivo de YAYAS. Negro total con detalles en lamina de oro real. Numero de edición en etiqueta interior. Solo 20 piezas.",
    short_description: "Hoodie eclipse lamina oro exclusivo",
    categories: [{ id: 22, name: "Premium", slug: "premium" }],
    images: [
      { id: 28, src: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&h=1000&fit=crop", alt: "ECLIPSE Gold Foil Hoodie" },
    ],
    sku: "ECLI-GOLD-001",
    tags: ["gold", "premium", "edicion-especial"],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
];

export const DEMO_CATEGORIES = [
  {
    id: 17,
    name: "Hoodies",
    slug: "hoodies",
    description: "Hoodies oversize y premium. La pieza estrella de YAYAS.",
    image: "https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=800&h=600&fit=crop",
    count: 4,
  },
  {
    id: 18,
    name: "Playeras",
    slug: "playeras",
    description: "T-shirts oversize, longsleeves y thermals.",
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&h=600&fit=crop",
    count: 5,
  },
  {
    id: 19,
    name: "Chaquetas",
    slug: "chaquetas",
    description: "Bomber jackets, leather look y varsity.",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop",
    count: 3,
  },
  {
    id: 20,
    name: "Pantalones",
    slug: "pantalones",
    description: "Cargo pants, wide-leg y joggers.",
    image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&h=600&fit=crop",
    count: 4,
  },
  {
    id: 21,
    name: "Accesorios",
    slug: "accesorios",
    description: "Gorras, bolsas, cadenas y más.",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&h=600&fit=crop",
    count: 6,
  },
  {
    id: 22,
    name: "Premium",
    slug: "premium",
    description: "Ediciones limitadas y drops exclusivos.",
    image: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&h=600&fit=crop",
    count: 3,
  },
];