import type { WooProduct } from "./types";

export const DEMO_PRODUCTS: WooProduct[] = [
  {
    id: 1,
    name: "VOID TEXTURE Tee",
    slug: "void-texture-tee",
    price: "850",
    regular_price: "1200",
    on_sale: true,
    stock_quantity: 12,
    stock_status: "instock",
    featured: true,
    description: "Playera de algodón orgánico con textura única en tono void. Diseño minimalista para quienes prefieren lo oscuro. 100% algodón mexicano.",
    short_description: "Playera dark con textura void",
    categories: [{ id: 1, name: "Playeras", slug: "playeras" }],
    images: [
      { id: 1, src: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&h=1000&fit=crop", alt: "VOID TEXTURE Tee" },
      { id: 2, src: "https://images.unsplash.com/photo-1618354691438-25bc04584c23?w=800&h=1000&fit=crop", alt: "VOID TEXTURE Tee Back" },
    ],
    sku: "VOID-TEE-001",
    tags: [],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
  {
    id: 2,
    name: "OBSIDIAN Hoodie",
    slug: "obsidian-hoodie",
    price: "1450",
    regular_price: "1450",
    on_sale: false,
    stock_quantity: 8,
    stock_status: "instock",
    featured: true,
    description: "Hoodie premium en color obsidiana. Material pesado, cálido y duradero. Estampado sutil en espalda.",
    short_description: "Hoodie premium obsidiana",
    categories: [{ id: 2, name: "Hoodies", slug: "hoodies" }],
    images: [
      { id: 3, src: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&h=1000&fit=crop", alt: "OBSIDIAN Hoodie" },
      { id: 4, src: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&h=1000&fit=crop", alt: "OBSIDIAN Hoodie Detail" },
    ],
    sku: "OBS-HOOD-001",
    tags: [],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
  {
    id: 3,
    name: "CARBON Crossbody Bag",
    slug: "carbon-crossbody",
    price: "680",
    regular_price: "850",
    on_sale: true,
    stock_quantity: 3,
    stock_status: "instock",
    featured: false,
    description: "Bolsa crossbody en color carbono. Tela resistente al agua, ideales para el día a día.",
    short_description: "Bolsa crossbody carbono",
    categories: [{ id: 3, name: "Accesorios", slug: "accesorios" }],
    images: [
      { id: 5, src: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&h=1000&fit=crop", alt: "CARBON Crossbody" },
    ],
    sku: "CARB-BAG-001",
    tags: [],
    attributes: [],
  },
  {
    id: 4,
    name: "BLOOD Logo Cap",
    slug: "blood-logo-cap",
    price: "420",
    regular_price: "420",
    on_sale: false,
    stock_quantity: 20,
    stock_status: "instock",
    featured: false,
    description: "Gorra con bordado del logo YAYAS. Cierre ajustable.",
    short_description: "Gorra logo YAYAS",
    categories: [{ id: 3, name: "Accesorios", slug: "accesorios" }],
    images: [
      { id: 6, src: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&h=1000&fit=crop", alt: "BLOOD Logo Cap" },
    ],
    sku: "BLOOD-CAP-001",
    tags: [],
    attributes: [],
  },
  {
    id: 5,
    name: "SMOKE Bomber Jacket",
    slug: "smoke-bomber-jacket",
    price: "1890",
    regular_price: "2200",
    on_sale: true,
    stock_quantity: 5,
    stock_status: "instock",
    featured: true,
    description: "Bomber jacket en tono smoke. Forro de satén, acabados premium.",
    short_description: "Bomber jacket smoke",
    categories: [{ id: 4, name: "Jackets", slug: "jackets" }],
    images: [
      { id: 7, src: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1000&fit=crop", alt: "SMOKE Bomber" },
    ],
    sku: "SMOK-BOM-001",
    tags: [],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L"] }],
  },
  {
    id: 6,
    name: "ASH Wide Pants",
    slug: "ash-wide-pants",
    price: "980",
    regular_price: "980",
    on_sale: false,
    stock_quantity: 15,
    stock_status: "instock",
    featured: false,
    description: "Pantalón wide leg en tela ash. Cómodo, oversize, oscuro.",
    short_description: "Pantalón wide ash",
    categories: [{ id: 5, name: "Pantalones", slug: "pantalones" }],
    images: [
      { id: 8, src: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&h=1000&fit=crop", alt: "ASH Wide Pants" },
    ],
    sku: "ASH-WID-001",
    tags: [],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
  {
    id: 7,
    name: "CREAM Essential Tee",
    slug: "cream-essential-tee",
    price: "590",
    regular_price: "590",
    on_sale: false,
    stock_quantity: 25,
    stock_status: "instock",
    featured: false,
    description: "Playera básica en tono cream. Para contrastar con outfits oscuros.",
    short_description: "Playera cream básica",
    categories: [{ id: 1, name: "Playeras", slug: "playeras" }],
    images: [
      { id: 9, src: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=1000&fit=crop", alt: "CREAM Essential" },
    ],
    sku: "CREA-TEE-001",
    tags: [],
    attributes: [{ id: 1, name: "Talla", options: ["S", "M", "L", "XL"] }],
  },
  {
    id: 8,
    name: "GOLD Chain Necklace",
    slug: "gold-chain-necklace",
    price: "350",
    regular_price: "450",
    on_sale: true,
    stock_quantity: 2,
    stock_status: "instock",
    featured: false,
    description: "Cadena dorada con dije YAYAS. Acero inoxidable chapado en oro.",
    short_description: "Cadena dorada YAYAS",
    categories: [{ id: 3, name: "Accesorios", slug: "accesorios" }],
    images: [
      { id: 10, src: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=1000&fit=crop", alt: "GOLD Chain" },
    ],
    sku: "GOLD-CHAIN-001",
    tags: [],
    attributes: [],
  },
];

export const DEMO_CATEGORIES = [
  { id: 1, name: "Playeras", slug: "playeras", description: "Colección de playeras oscuras", image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&h=600&fit=crop", count: 2 },
  { id: 2, name: "Hoodies", slug: "hoodies", description: "Hoodies premium", image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&h=600&fit=crop", count: 1 },
  { id: 3, name: "Accesorios", slug: "accesorios", description: "Accesorios para completar tu look", image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&h=600&fit=crop", count: 3 },
  { id: 4, name: "Jackets", slug: "jackets", description: "Jackets y abrigos", image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=600&fit=crop", count: 1 },
  { id: 5, name: "Pantalones", slug: "pantalones", description: "Pantalones anchos y cómodos", image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&h=600&fit=crop", count: 1 },
];